# Generated by Django 6.1.1 on 2026-09-19 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('idEmprendimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('totalVistas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vistas',
            fields=[
                ('idVisita', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHora', models.DateTimeField(auto_now_add=True)),
                ('idEmprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vistas', to='emprendimientos.emprendimiento')),
            ],
        ),
    ]
